version: "3.9"
services:
  app:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - ./docs:/app/docs               # hot-reload insights file
      - ./Desktop/Research\ Papers:/papers:ro
    environment:
      OPENAI_API_KEY: ${OPENAI_API_KEY}
      DAILY_TOKEN_BUDGET: "200000"